Repository HansBlackCat/SCSC21SSIG-ProgrammingPractice, pull requests merged in 2021-06, with the labels that each got.

#6 added Problem0 ans
  WG-Go/week0/week0.rs
Labels: ProblemSolved

#5 Problem 0
  HansBlackCat/week0/week0.c
Labels: ProblemSolved

#4 Problem00 solved
  dongwook0826/Problem00/C++/HelloSIG.cpp
  dongwook0826/Problem00/Haskell/HelloSIG.hs
  dongwook0826/Problem00/Java/HelloSIG.java
  dongwook0826/Problem00/Julia/HelloSIG.jl
  dongwook0826/Problem00/Python/HelloSIG.py
  dongwook0826/Problem00/R/HelloSIG.R
Labels: ProblemSolved

#7 Add gitignore & change README
  .gitignore
  README.md
Labels: enhancement

#8 Add Tutorial
  HowToBranch.md
  README.md
  img/branch.png
  img/gitid.png
Labels: documentation

#10 Added Problem01 solution & restructured hierarchy for problem files
  README.md
  __MainProblem__/Problem00.md
  __MainProblem__/Problem01.md
  __MainProblem__/img/640px-Red-black_tree_example.svg.png
  __MainProblem__/img/unbalanced_bst.jpg
  __SubProblem__/SubProblem01.md
  __SubProblem__/img/1024px-Pentomino_Puzzle_Solution_8x8_Minus_Center.svg.png
  __SubProblem__/img/1024px-Sudoku_Puzzle_by_L2G-20050714_standardized_layout.svg.png
  __SubProblem__/img/Encoded_exact_cover_problem.png
  __SubProblem__/img/N_queen.png
  __SubProblem__/img/four-way-linked.jpeg
  dongwook0826/Problem01/Haskell/RBTree.hs
  dongwook0826/Problem01/Haskell/RBTreeMain.hs
  dongwook0826/Problem01/Haskell/__solution__.md
Labels: ProblemSolved, documentation
